/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AbountUs: typeof import('./src/components/AbountUs.vue')['default']
    AboutUs: typeof import('./src/components/AboutUs.vue')['default']
    ContactUs: typeof import('./src/components/ContactUs.vue')['default']
    FeaturedProducts: typeof import('./src/components/FeaturedProducts.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Testimonials: typeof import('./src/components/Testimonials.vue')['default']
  }
}
