/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutUs: typeof import('./src/components/AboutUs.vue')['default']
    Auth: typeof import('./src/components/Auth.vue')['default']
    ContactUs: typeof import('./src/components/ContactUs.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    Profile: typeof import('./src/components/Profile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Testimonials: typeof import('./src/components/Testimonials.vue')['default']
  }
}
